WINDOW_WIDTH = 640
WINDOW_HEIGHT = 360
WINDOW_SIZE = WINDOW_WIDTH, WINDOW_HEIGHT

WINDOW_SCALE = 2
SCALED_WINDOW_SIZE = WINDOW_WIDTH*WINDOW_SCALE, WINDOW_HEIGHT*WINDOW_SCALE

FRAMERATE = 100

CAPTION = "LD57"